---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Kyiv
      - WEBUI_PORT=8181
    volumes:
      - /storage/data/qbittorrent/config:/config
      - /storage/downloads:/downloads
    ports:
      - 8181:8181
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
